# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biIyIUYeFwCOqQ7msLKM_ZV-I-66pCM1
"""

!pip install pyarrow==14.0.1 requests==2.31.0
!pip install streamlit
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps xformers "trl<0.9.0" peft accelerate bitsandbytes

# Create the Streamlit app file
with open('app.py', 'w') as f:
    f.write('''
import streamlit as st
import torch
from unsloth import FastLanguageModel

# Configuration parameters
max_seq_length = 2048
dtype = None
load_in_4bit = True

# Define alpaca_prompt template
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

# Load FastLanguageModel
@st.cache_resource(show_spinner=False)
def load_model():
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="bsc-9/AI_Cooking_Kitchen",  # Replace with your trained model name
        max_seq_length=max_seq_length,
        dtype=dtype,
        load_in_4bit=load_in_4bit,
    )
    FastLanguageModel.for_inference(model)  # Enable native 2x faster inference
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    return model, tokenizer, device

model, tokenizer, device = load_model()

# Streamlit app interface
st.title("Chef Assistant Recipe Generator")

# User inputs
name = st.text_input("Enter your name", "Chef")
instruction = st.text_input("Instruction", f"{name}, you are a professional chef assistant. Make a dish by firstly presenting it, then listing the ingredients and finally the recipe step by step in bullet points under the following input requirements.")
requirements = st.text_input("Requirements", "Requires 60 minutes preparation or less and it contains at least this ingredients chicken biryani")

if st.button("Generate Recipe"):
    # Generate the recipe
    prompt = alpaca_prompt.format(instruction, requirements, "")
    inputs = tokenizer([prompt], return_tensors="pt").to(device)

    outputs = model.generate(**inputs, max_new_tokens=512, use_cache=True)
    recipe = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Display the recipe
    st.subheader("Generated Recipe")
    st.write(recipe + "\\n\\nThank you for making me your cooking assistant!")
''')

# Run the Streamlit app using a background process and localtunnel to tunnel the output
import subprocess
import time

# Kill any existing streamlit processes
!kill -9 $(lsof -t -i:8501)



# Allow the Streamlit app to start
time.sleep(5)

# Create a tunnel to the Streamlit app
!streamlit run app.py & npx localtunnel --port 8501

